# Generated by Django 5.1.6 on 2025-04-08 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, upload_to='img/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('crm', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('criacao_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone', models.CharField(max_length=20)),
                ('imagem', models.ImageField(blank=True, upload_to='img/%Y/%m')),
                ('ativo', models.BooleanField(default=True)),
                ('mensagem', models.TextField(blank=True)),
                ('especialidade_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sistema.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('A', 'Agendada'), ('C', 'Cancelada'), ('M', 'Confirmada'), ('R', 'Realizada')], default='A', max_length=1)),
                ('medico_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.medico')),
                ('paciente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.paciente')),
            ],
        ),
    ]
